baseURL = "/"
title = "Coding Problems"
theme="harbor"
author = "Hitarth Thummar"
copyright = "Free use for all //"
enableGitInfo = true
DefaultContentLanguage = "en"
enableInlineShortcodes = true
languageCode           = "en"
paginate               = 15
disqusShortname = "codingproblems"
ignoreErrors = ["error-remote-getjson"]

[Params.color]
bg     = "white"
border = "black"
link   = "#3d84ff"
text   = "black"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
